# Generated by Django 5.1.4 on 2025-04-02 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coach", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="videoanalysis",
            name="processed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Process_date"
            ),
        ),
        migrations.AddField(
            model_name="videoanalysis",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="video_analyses",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="videoanalysis",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="videoanalysis",
            name="uploaded_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Upload_date"),
        ),
    ]
