# Generated by Django 5.1.4 on 2024-12-30 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='message',
            new_name='messenger_m_senderI_95f135_idx',
            old_name='message_senderI_081a93_idx',
        ),
        migrations.AlterModelTable(
            name='message',
            table=None,
        ),
    ]
