# Generated by Django 5.1.4 on 2024-12-30 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SendTime', models.DateField(auto_now_add=True)),
                ('Checked', models.BooleanField(default=False)),
                ('Content', models.TextField()),
                ('receiverID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('senderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'message',
                'indexes': [models.Index(fields=['senderID', 'receiverID'], name='message_senderI_081a93_idx')],
            },
        ),
    ]
