# Generated by Django 5.1.4 on 2025-01-01 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='DislikesCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='LikesCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='postmark',
            name='PostID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postmark_set', to='feed.post'),
        ),
    ]
